### ISSUE TITLE
Electron builder

### ISSUE THREAD

**Issue by alexcroox** [epilande/yarems#7]
Have you ever attempted to integrate electron builder with this boilerplate? I'm looking to release the app I've built but struggling to get started. I've previously released a vuejs one but much of this was taken care of and wondered if you would consider adding electron-builder to the boilerplate so users can go from development to release?

Inspiration: https://github.com/SimulatedGREG/electron-vue/tree/master/template

**Comment by alexcroox** [comment]
Apologies just realised it's already using electron-packager, it was as simple as changing:

`"main": "./dist/bundle.js"` so that `"dist": "electron-builder"` can work.

Edit, OK it builds without error but errors immediately after launching the .app with `window is not defined`. So I'm guessing just bundle.js isn't what I need.

**Comment by epilande** [comment]
I'm open to it. Is `electron-builder` the recommended way for packaging electron applications?

Need to catch some sleep right now, I'll look into this tomorrow.

**Comment by alexcroox** [comment]
I’ve used it in the past mainly because of the autoupdating features built in. One of the biggest concerns for me when releasing an app is how do I allow the users to easily get the latest version (most wont bother manually downloading and installing again and again)

**Comment by alexcroox** [comment]
That and code signing the application. It basically has a lot of features for releasing a truly production/distribution ready app.

**Comment by epilande** [comment]
Good point. I made some progress on this over the weekend. I just merged a PR (https://github.com/epilande/yarems/pull/9) that swaps out `electron-packager` with `electron-builder`. I ran into a couple of roadblocks along the way but eventually got it to build properly 😅 

A couple of gotchas regarding the PR:
- Currently, the `package` command will only build for MacOS. I'd like to build for other OS as well though I have no way to test on other systems...PR welcome 😃 
- `main` in `package.json` needs to point to `main.js`. It will run in the main process, hence your error with `window is not defined` since `window` is only available in the renderer process.
- I had to remove `import` statements in `main.js` since we're serving `main.js` as is..it's not being transpiled with `webpack`/`babel`. Though it shouldn't be hard to set those up but to keep this boilerplate to a bare minimum, a quick fix is to change those imports to `const` & `require`.

Hopefully that helps. I still have a lot to learn with `electron-builder`. 

I haven't been developing electron apps lately but I definitely want to get back into it once I find some time. Anyways I appreciate all the feedback and thanks for pointing out `electron-builder`, it definitely offers more than `electron-packager`. ✌️

**Comment by alexcroox** [comment]
Wow nice work thank you so much! Multi platform builds should be OK. With my last electron project I could build macOS + Windows from my macOS machine, but linux builds had to be auto added to releases via a travis build step (because of the binaries in my project). I'll let you know how this works for ths boilerplate once I have it setup in case it's of any interest/use.

Shame about no full es6 in the main process but I can understand your reasoning!

I'll try implementing these updates in my app and report back any issues.

Thanks again!!

**Comment by alexcroox** [comment]
Got this working tonight thank you! The one modification I had to make was adding `'babel-polyfill'` to the entry config in both webpack configs. Otherwise my async functions in the renderer process wouldn't work (ReferenceError: regeneratorRuntime is not defined)
